name: Service Deploy

on:
  workflow_dispatch:

jobs:
  deploy_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment specific variables
      uses: jnus/json-variables@v1.0
      with:
        scope: deploy
        configFile: './Variables/Actions.json'
        secrets: '${{ toJson(secrets) }}'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_IMAGE }}:latest
        provenance: false